server.port=8081

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/food_order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Camunda 7 configuration
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.admin-user.first-name=Admin
camunda.bpm.admin-user.last-name=User
camunda.bpm.admin-user.email=admin@localhost
camunda.bpm.filter.create=All Tasks
camunda.bpm.database.schema-update=true
camunda.bpm.job-execution.enabled=true

# Logging Configuration
logging.level.org.camunda.bpm.spring.boot=INFO
logging.level.org.apache.activemq=WARN
logging.level.com.example.foodorder=INFO
